title: "Sentinelfox Knowledge Hub"
description: "Internal knowledge base for our team"
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

include:
  - _layouts
  - _includes
  - assets

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: custom
